Add a helper class for implementing clap_context_menu_builder
free-audio/clap-helpers pull request #18
Opened 2023-04-14 18:50 UTC by jatinchowdhury18

I tried to copy the patterns that were being used in the other helper classes, but please let me know if there's things that are missing, or are in the wrong locations.

2023-04-14 18:50 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/signed)](https://cla-assistant.io/free-audio/clap-helpers?pullRequest=18) <br/>All committers have signed the CLA.

2023-04-17 07:14 UTC, abique requested changes

2023-04-17 07:14 UTC, abique commented on include/clap/helpers/context-menu-builder.hh
> +      virtual bool supports(clap_context_menu_item_kind_t item_kind) { return false; }
This one should be `const noexcept` maybe?

2023-04-17 07:14 UTC, abique commented on include/clap/helpers/context-menu-builder.hh
> +      ContextMenuBuilder() = default;
Missing virtual dtor.

2023-04-17 07:14 UTC, abique commented on include/clap/helpers/context-menu-builder.hh
> +      ContextMenuBuilder() = default;
ctor should be protected I think.

2023-04-17 07:14 UTC, abique commented on include/clap/helpers/context-menu-builder.hh
> +      virtual bool addItem(clap_context_menu_item_kind_t item_kind, const void *item_data) {
I think `addItem` should be pure virtual, because if it isn't implemented the subclass is pointless right?

2023-04-17 07:14 UTC, abique commented on include/clap/helpers/context-menu-builder.hh
> +      virtual bool supports(clap_context_menu_item_kind_t item_kind) { return false; }
Same, it should be pure virtual because if you don't impl it nothing is supported which makes the subclass pointless.

2023-04-17 15:47 UTC, jatinchowdhury18 commented
Thanks for the comments, I've updated the PR accordingly. I agree that making `addItem()` and `supports()` pure virtual is the right choice. Also thanks for catching the missing destructor :).

2023-04-17 16:04 UTC, merged

2023-04-17 16:04 UTC, abique commented
Thank you :+1: